[alias]
gateway = "run --bin constella_db -- run-gateway"
node = "run --bin constella_db -- run-node"
client = "run --bin constella_db -- run-client"
 

# this way i just need to do cargo net to run the network module seperately
